### ISSUE TITLE
碰到的一些问题

### ISSUE THREAD

**Issue by xiangjt** [LeongAndroid/Launcher3#1]
我用了一下这个launcher，发现了一些问题
1. 本应用的icon也会显示在桌面
2. 应用第一次启动后，只能显示第一屏，然后等了几秒钟，后几屏才会出现，并且会把当前屏幕滑动到最后一屏
3. 新安装应用没有放到最后一屏，而是在前面找了一个空位放上去了（只看到一次，后面没有测试了）

**Comment by LeongAndroid** [comment]
1.本应用是指Launcher本身的图标吗？这个应该是<category android:name="android.intent.category.LAUNCHER" />这个属性控制的，只有这个属性才会显示的，现在这个Launcher没有加。
2.第一屏的图标都是在default_workspace.xml文件中配置的，后面没有配置的都会加到屏幕上，屏幕也会滚动到新加应用的那一页上，原生的设计。
3.看代码，默认应该是从第2页开始添加应用。
AddWorkspaceItemsTask.java
findSpaceForItem这个方法：
int screenCount = workspaceScreens.size();
        // First check the preferred screen.
        int preferredScreenIndex = workspaceScreens.isEmpty() ? 0 : 1;
        if (preferredScreenIndex < screenCount) {
            screenId = workspaceScreens.get(preferredScreenIndex);
            found = findNextAvailableIconSpaceInScreen(
                    app, screenItems.get(screenId), cordinates, spanX, spanY);
        }

        if (!found) {
            // Search on any of the screens starting from the first screen.
            for (int screen = 1; screen < screenCount; screen++) {
                screenId = workspaceScreens.get(screen);
                if (findNextAvailableIconSpaceInScreen(
                        app, screenItems.get(screenId), cordinates, spanX, spanY)) {
                    // We found a space for it
                    found = true;
                    break;
                }
            }
        }

        if (!found) {
            // Still no position found. Add a new screen to the end.
            screenId = LauncherSettings.Settings.call(app.getContext().getContentResolver(),
                    LauncherSettings.Settings.METHOD_NEW_SCREEN_ID)
                    .getLong(LauncherSettings.Settings.EXTRA_VALUE);

            // Save the screen id for binding in the workspace
            workspaceScreens.add(screenId);
            addedWorkspaceScreensFinal.add(screenId);

            // If we still can't find an empty space, then God help us all!!!
            if (!findNextAvailableIconSpaceInScreen(
                    app, screenItems.get(screenId), cordinates, spanX, spanY)) {
                throw new RuntimeException("Can't find space to add the item");
            }
        }

大概意思就是如果之前存在页面的话，就从第2页开始找空白位置，如果找不到就新建新的一页，再去找位置。

**Comment by xiangjt** [comment]
谢谢答复，你的代码很有用
